#!/bin/bash

sInterfaceName="wlan0"
sIpAddress=`/sbin/ifconfig $sInterfaceName | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
sLogPath=/opt/wireless-monitor/log/wireless-monitor.log

if ! [ $sIpAddress ]
then
	echo "[$(date +'%Y-%m-%d %T')] Forcing up [ $sInterfaceName ]" >> $sLogPath
	RC=(`/sbin/ifup --force $sInterfaceName >/dev/null; echo $?`)
	if [ $RC -eq 0 ]
	then
		echo "[$(date +'%Y-%m-%d %T')] Interface [ $sInterfaceName ] restarted" >> $sLogPath
	else
		echo "[$(date +'%Y-%m-%d %T')] Failed to restart interface [ $sInterfaceName ]" >> $sLogPath
	fi
#else
#	echo "[$(date +'%Y-%m-%d %T')] Interface [ $sInterfaceName ] Ip Address [ $sIpAddress ]" >> $sLogPath
fi

